### ISSUE TITLE
empty string or null in db

### ISSUE THREAD

**Issue by adrianandreias** [rpkilby/jsonfield#100]
Hello,

Wouldn't it be nice to gracefully handle empty string or NULL when reading from db? It could default to empty dictionary: {}.

I've added the field to my model manually to the DB table and it did not work with empty string I had to update my_table set settings='{}'.

I know I can set the '{}' via the south migrations, but it would still be a nice default behavior.

**Comment by EmilStenstrom** [comment]
@bradjasper Do you have a source for "" being valid json? json.org hints that an object or array at the top level is required (but doesn't say so explicitly). jsonlint.com says "" or "hello" are invalid json strings.

**Comment by bradjasper** [comment]
Hey @EmilStenstrom — the best I can currently find are http://stackoverflow.com/questions/18419428/what-is-the-minimum-valid-json and http://stackoverflow.com/questions/7487869/is-this-simple-string-considered-valid-json

It would make things much easier to only allow [] and {}, but I'm not sure if that's the expected behavior (especially at this point). Am definitely open to hearing more thoughts about this though if people are interested in exploring it.

**Comment by EmilStenstrom** [comment]
Hey! So it seems your can decide if you want to follow RFC-4627 or EMCA-404. In the context of a database field I strongly doubt people use it to store simple JSON values. All the other column types are better for that.

**Comment by bradjasper** [comment]
I'm open to supporting a RFC-4627 version and then migrating towards making it the default over time if that's the preferred option—is anyone primarily storing simple JSON values?

I am planning some major work on django-jsonfield and this will be something I address.

**Comment by zbyte64** [comment]
json.loads("") vs json.loads('""')

OP is not referring to '""' but "". If a JSONField is blank in django the DB will read "" and JSONField will raise an exception that you cannot hope to fix unless you manually execute SQL.

**Comment by zbyte64** [comment]
So I am going to fork this but It would be nice to send a good pull request. I've seen others have to do this as well:
https://github.com/Nuevosmedios/django-jsonfield/commit/9a8c1bac97617f4aa748e85df51ce545f63e323e

I can think of a few different ways to handle this issue:
* check for blank option and allow empty string
* add on_bad_value option which is called on JSON parse error and can either raise a new error or return a value to be used in place

I am going to go for option 1 and implement it wherever I see checks for the null option.

**Comment by alesdotio** [comment]
We have ran into the same issue. Any updates regarding this?

**Comment by rpkilby** [comment]
Hi all. Null values are correctly loaded by the field, however the problem of loading empty strings (or more generally, any invalid JSON) has been handled by issuing a `RuntimeWarning` and loading the value as a plain string. If this field were to be immediately re-saved, then the value would be correctly serialized. e.g., with an empty string (`''`), it would be saved as (`'""'`).
