### ISSUE TITLE
Issue #52 returned

### ISSUE THREAD

**Issue by shaib** [rpkilby/jsonfield#116]
Hi,

We've just seen, on 1.0.0, an almost exact repetition of issue #52 where trying to populate a jsonfield in the middle of a South datamigration fails with an attribute-error on "id", in the case that the JsonField happens to come before the id field in the iteration of the dictionary of fields.

The issue was fixed in #53, but it seems now the code that tries to get the field value is no longer wrapped in a try..catch; further -- probably because of other changes in django-jsonfield -- the error thrown now is a KeyError rather than an AttributeError.

**Comment by bradjasper** [comment]
@shaib good catch. I have reverted this change in 1.0.2 but am leaving this ticket open because there needs to be a regression test for this.

**Comment by shaib** [comment]
@bradjasper thanks for the amazingly quick response; as I pointed out, the exception we actually saw was a KeyError, not AttributeError (pulling the actual traceback from the environment where we saw this was a little bit tricky, sorry). Perhaps this is due to a change in Django core. Either way, as you say, a regression test would verify that everything which needs to be caught, is caught indeed.

**Comment by bradjasper** [comment]
Thanks for the update, I will check in on this when I create the regression
test and try and catch both.
