### ISSUE TITLE
Default value question

### ISSUE THREAD

**Issue by mihaicc** [rpkilby/jsonfield#125]
Defining a model jsonfield and giving the default value as an empty dict:

``` python
JSONField(default={}, null=False, blank=True, max_length=5000)
```

might raise problems: http://reinout.vanrees.org/weblog/2012/04/18/default-parameters.html

Are we sure this is not the case with this lib?
Past versions accepted default value as string ('{}') but at 1.0.3 it's mandatory.

**Comment by domenkozar** [comment]
What about `lambda: {}`

**Comment by rtibbles** [comment]
Internally, jsonfield does a deepcopy of the object, so this should not be an issue.

**Comment by rtibbles** [comment]
https://github.com/dmkoch/django-jsonfield/blob/master/jsonfield/fields.py#L142
