### ISSUE TITLE
get_db_prep_value saving None as string 'null'

### ISSUE THREAD

**Issue by gmeans** [rpkilby/jsonfield#126]
I was looking to add a JSONField that can't be null and ran into JSONField saving a None value when the field is set to not allow NULL as a string 'null'. It appears to be right here:

https://github.com/bradjasper/django-jsonfield/blob/master/jsonfield/fields.py#L100

Is this intentional for some reason? I'd assume it should return None if the value is None so that database constraints could take over, but wanted to check if this was intentional before submitting a PR.

Thanks!

**Comment by bradjasper** [comment]
This is currently an open issue, with more info available at: https://github.com/bradjasper/django-jsonfield/issues/100

The plan is to support both types of JSON (RFC-4627 or EMCA-404)—but work hasn't started yet.

I'd be happy to accept a pull request if you wanted to take a shot at this.

**Comment by gmeans** [comment]
In our use case, we wanted the DB to prevent None / NULL like a standard field would do if null=False. So we made the following change:

https://github.com/gmeans/django-jsonfield/commit/9f30ff761185a9af6cd4cf676e2c41a6de34b08a

The original code was calling json.dumps() if the value was None and the field was configured with null = False. This resulted in the field not raising an IntegrityError if it was set to None due to json.dumps() returning 'null' as a string.

IMO Python None should always be database NULL so things behave as expected. I'd prefer to handle an IntegrityError as opposed to parsing the field out for 'null'.

Probably a bit narrower view than supporting the specs you listed, but if you agree I'll fire off a PR.

Thanks!

**Comment by bradjasper** [comment]
The main issue is this change will need to be deeply tested, as this package has had regressions in the past from small changes like this.

My hope was to get my hands around this with a better set of tests soon—but so far have been busy with other items.

I'd be happy to accept a PR for this—but wouldn't be able to pull it in until this case was thoroughly covered in tests.

**Comment by rpkilby** [comment]
Closed in favor of #100. In short, the rewrite should handle JSON strings. I borrowed from Django's postgres field here, and decoded strings are wrapped in a `JSONString` class, which prevents duplicate decodings such that `'""'` => `''` => 💥  no longer happens.
