### ISSUE TITLE
How do I filter based on a django-jsonfield?

### ISSUE THREAD

**Issue by lsmag** [rpkilby/jsonfield#127]
Hi,

I'm using Python3 and Django 1.7.8 and having the issue below:

```
# Saved something with value=1 before, then
> MyModel.objects.filter(value=1)
[]

> cmd = MyModel.objects.filter(value=1)
> MyModel.objects.filter(str(cmd.query))[0]
<MyInstance value=1>

# Logically
> MyModel.objects.raw('SELECT * FROM my_model_table WHERE value = "1"')[0]
<MyInstance value=1>
```

I don't know exactly why this is happening. Is there something I'm doing wrong or is this some kind of limitation of jsonfield?

**Comment by lsmag** [comment]
I think I figured out, `.filter` apparently only works when `value` is a string:

    > MyModel.objects.filter(value="foo")
    [<MyInstance value="foo">]

    > MyModel.objects.filter(value={'foo': 'bar'})
    []

Why is that? I'm using a custom queryset but even using `Queryset.filter(self, value=1)` it doesn't work.

**Comment by SMesser** [comment]
From what I can tell, dumps() is called twice during lookup, but only once during save. I think this tracks back to ambiguity in Django's documentation around the uses of get_prep_lookup() vs. get_db_prep_lookup(), but I haven't found the redundancy explicitly in the source. I was able to get get() and filter() to work properly by subclassing JSONField and overriding get_prep_lookup() on the subclass with a NOP:

> def get_prep_lookup(self, lookup_type, value):
>      return value

YMMV

**Comment by rpkilby** [comment]
In general, `JSONField` is _not_ intended to be queried - for that, you should probably use Django's builtin postgres `JSONField`. That said, we should support basically exact value or null checking. 

Leaving this open to ensure we test basic query support.
