### ISSUE TITLE
Key error on accessing JSONField created after Migration

### ISSUE THREAD

**Issue by stripathi669** [rpkilby/jsonfield#144]
Hi

I am using django 1.8 with postgres 9.4. I'm facing a situation where accessing JSONField created through migrations (not present when table was created) throws key error.

Steps to reproduce:
1. Suppose there is model `ABC`. `ABC` contains several records intially.
2. Add a field to model:
   
   class ABC(models.Model):
          # Lots of fields
          link_meta = JSONField(null=True, blank=True)
3. Run `python manage.py makemigration` and `python manage.py migrate`

After this accessing `link_meta` field for any record of `ABC` throws this error:

```
File "/app/.heroku/python/lib/python2.7/site-packages/jsonfield/subclassing.py", line 34, in __get__
return obj.__dict__[self.field.name]
KeyError: 'link_meta'
```

**Comment by alekseyev** [comment]
Have the same problem here. Having null values in JSON field leads to `KeyError` in line 34 of `subclassing.py`. Weirdly, I don't get this error in shell, but I get it when I try to access a particular object in tastypie API.

Django 1.11.12, django-jsonfield 2.0.2

**Comment by rpkilby** [comment]
Closing in favor of #198.
