### ISSUE TITLE
Ensure decimals can be serialized

### ISSUE THREAD

**Issue by mzu** [rpkilby/jsonfield#161]
Hi,

I just upgraded Django from 1.5 to 1.8 and I am now running into issues with version 1.0.3 of jsonfield.

I am getting the following Error message when I try to save a dict on a `jsonfield.JSONField()`. The dict contains some Decimals:

`Decimal('20.00') is not JSON serializable`

I assume this is because Django is not supporting 'simplejson' anymore?

Is there a way to fix this on my side?

Thanks!
Mischa

**Comment by frewsxcv** [comment]
Decimals are intentionally not serializable since they can either be represented as a string or float, depending on what the user wants (both are valid in different scenarios).

**Comment by jdt1204** [comment]
We ran across this issue, and from what we found, it's not due to Django 1.8 and above. It's actually an issue with django-jsonfield. In case anyone is interested in a workaround, the ```django-jsonfield``` package, version ```0.9.15``` will support Decimal serialization. Just run the following: 

```bash 
pip3 install django-jsonfield==0.9.15
```

Given that you're using the package ```django-jsonfield```, that should fix your problem.

**Comment by matteius** [comment]
I just ran into this issue upgrading django-jsonfield, whereas older versions supported serializing Decimal, the newer version requires that people using the library possible write more code to parse the data being passed into the field.   I find this counter intuitive, and will point out a counter example.  In celery 3.x series it would not serialize Decimals in the task arguments, but Celery 4.x series fixed this so it is easier to use the Json serializer.   Food for thought.

**Comment by rpkilby** [comment]
Hi all, closing as this is covered by `test_decimal_in_json_field`.
