### ISSUE TITLE
Unable to query by serialized data

### ISSUE THREAD

**Issue by simondrabble** [rpkilby/jsonfield#162]
I'm unable to perform a search (either directly or by filter) against the json field contents:

```
>>> data = {'text': 'some value'}
>>> qs = SomeJsonFieldModel.objects.filter(data=data)
>>> qs.count()
0
>>>
```

I've uploaded a test case that exposes the issue here: https://github.com/simondrabble/jsonbug, which contains an explanation of what's going on. Unfortunately this issue is a blocker for me since I need to encode search parameters into a json field and serialize uniquely.

**Comment by audiolion** [comment]
Are you using sqlite as your database? I ran into this issue where when testing against MySQL I can filter on the `jsonfield`, however `sqlite` doesn't work
