### ISSUE TITLE
Use DjangoJSONEncoder instead of self written one

### ISSUE THREAD

**Issue by sspross** [rpkilby/jsonfield#166]
We tried to store a timezone aware datetime field. This throws an error in your self written json encoder. I would recommend to use DjangoJSONEncoder from django to support this kind of types as well:

https://docs.djangoproject.com/en/1.9/topics/serialization/

Sorry I don't have the time to create a pull request, we can live without the timezone details atm. Regards and thanks for your work anyway!

**Comment by mariodev** [comment]
I think this issue can be closed, since jsonfield uses DRF encoder (which I imagine is already more powerful then the built-in one for django).

Also it's easy to override the encoder as well.

```
field = JSONField(dump_kwargs={'cls': CustomJSONEncoder})
```

**Comment by rpkilby** [comment]
Hi @mariodev - you are correct.
