### ISSUE TITLE
Problems with non-AutoField primary key models.

### ISSUE THREAD

**Issue by iciclespider** [rpkilby/jsonfield#195]
JSONField does not work properly with models that define their own primary key fields when a new instance is created. Any string json values passed in during construction will be attempted to be loads'ed as a json string.

The follow test reproduces the problem.
```
class KeyedJsonModel(models.Model):
    key = models.CharField(max_length=32, primary_key=True)
    json = JSONField()

class KeyedJSONFieldTest(TestCase):

    json_model = KeyedJsonModel

    def test_integer_in_string_in_json_field(self):
        """Test saving the Python string '123' in our JSONField"""
        json_obj = '123'
        obj = self.json_model.objects.create(key='test_integer_in_string',
                                             json=json_obj)
        new_obj = self.json_model.objects.get(pk=obj.pk)

        self.assertEqual(new_obj.json, json_obj)
```

**Comment by dcecile** [comment]
Our workaround was to use a default value, e.g.

```py
class KeyedJsonModel(models.Model):
    key = models.CharField(max_length=32, primary_key=True)
    json = JSONField(default="{}")
```

**Comment by rpkilby** [comment]
Hi. I don't believe this is an issue with the primary key. Instead, jsonfield has had issues with serializing/deserializing string values. See https://github.com/rpkilby/jsonfield/issues/243#issuecomment-587145911 for more details.
