### ISSUE TITLE
Empty string in database renders admin unusable.

### ISSUE THREAD

**Issue by francescortiz** [rpkilby/jsonfield#199]
IMHO, a wrong value stored in the database shouldn't break the django admin. Also, an empty string doesn't feel like a faulty value to me.

**Comment by iuliux** [comment]
Related to #100

**Comment by rpkilby** [comment]
Hi. This has been generally fixed by handling all invalid JSON values. A RuntimeWarning is issued, however the value is still loaded as a string.
