### ISSUE TITLE
Non-ASCII characters displayed as escape sequences in Django administration

### ISSUE THREAD

**Issue by ru13r** [rpkilby/jsonfield#205]
Hello,

Currently non-ASCII characters are displayed as Unicode escape sequences in Django admin text field, which makes it un-editable in languages other than English. I suggest adding `ensure_ascii=False` to return of `dumps_for_display` function in `JSONField` class to make it more usable.

The option might be passed as a `dump_kwarg` as well.

    class JSONField(JSONFieldBase, models.TextField):
        """JSONField is a generic textfield that serializes/deserializes JSON objects"""
        form_class = JSONFormField
    
        def dumps_for_display(self, value):
            kwargs = {"indent": 2}
            kwargs.update(self.dump_kwargs)
            return json.dumps(value, **kwargs, ensure_ascii=False)

**Comment by dmkoch** [comment]
Please submit a pull request if possible.

**Comment by vpavlenko** [comment]
@ru13r Thanks a lot for the fix! @dmkoch Could you please make a release so it could be easily installed using pip?
