### ISSUE TITLE
dict will be converted to string in serializers.ModelSerializer

### ISSUE THREAD

**Issue by josh7** [rpkilby/jsonfield#208]
can not used in serializers.ModelSerializer

such as:

```
class ConfigSerializer(serializers.ModelSerializer): 
    class Meta: 
        model = Config 
        fields = ( 'id', 'name', )
```
expected:
```
{
    "id": 1,
    "name": "one"
}
```
now:
```
"{'id':1,'name':'one'}"
```

**Comment by alantrick** [comment]
The bug report is a little unclear. The problem here is basically that django-rest-framework doesn't have any native support for this library.

**Comment by stsewd** [comment]
There is a solution for this https://github.com/dmkoch/django-jsonfield/issues/188#issuecomment-300439829

**Comment by rpkilby** [comment]
Closing as I don't want to explicitly test DRF support and also given that we test against Django's builtin serializers. That said, I'm happy to take a second look at any DRF compatibility issues.
