### ISSUE TITLE
JSONFormField subclasses CharField instead of TextField

### ISSUE THREAD

**Issue by andirigible** [rpkilby/jsonfield#211]
`class JSONFormField(JSONFormFieldBase, fields.CharField)`

Is this intentional? I would assume not, as the very next class declaration is a `JSONCharFormField` with the exact same superclasses.

**Comment by rpkilby** [comment]
Hi @andirigible. There is no `forms.TextField`. Instead, `models.TextField.formfield` passes the `Textarea` widget when creating its form field.
