### ISSUE TITLE
Migration issue: badly-written custom field

### ISSUE THREAD

**Issue by gamesbook** [rpkilby/jsonfield#219]
Python 3.5
Django 1.11

When I try to migrate between code on one machine, which has been patched to use django-jsonfield, and another machine, I get this error:

```
ValueError: Cannot alter field uploads.UploadData.data_set into uploads.UploadData.data_set - 
they do not properly define db_type (are you using a badly-written custom field?)
```
In this case the `data_set` field is the one defined as  a `JSONField`.

**Comment by rpkilby** [comment]
Hi @gamesbook. `JSONField` has been rewritten to use Django's migration machinery instead of South's, and this should no longer be an issue. Please let me know if you run into any issues though. Thanks!
