### ISSUE TITLE
RFC 4627 Obsolete

### ISSUE THREAD

**Issue by pedfercue** [rpkilby/jsonfield#220]
According to RFC 4627 the root of a JSON must be an array or object and this is how the behavior of this package. But RFC 4627  wass obsoleted by the latter RFC 7159 and the root of A JSON is no longer required to be an object or array and I think this package should be updated accordingly.

(Extract from RFC 7159)
A JSON value MUST be an object, array, number, or string, or one of the following three literal names:
false
null
true

**Comment by rpkilby** [comment]
Hi all. v3.0 has just been released, which should support any valid JSON value. Please let me know if you have any issues. Thanks!
