### ISSUE TITLE
need a optional param to excute dumps_for_display

### ISSUE THREAD

**Issue by clevertang** [rpkilby/jsonfield#227]
`class AllocateRuleTab(models.Model):`
	`id = PositiveAutoField(primary_key=True)`
	`whs_id = models.CharField(max_length=4)`
	`extra = JSONField()`
	`ctime = TimestampField(auto_now_add=True)`
	`mtime = TimestampField(auto_now=True)`
here we create a object 
`AllocateRuleTab.objects.create(whs_id=whs_id, extra=[{'name':1},{'name':2}])`
i just want auto json.loads and json.dumps
when i use 
`item = AllocateRuleTab.objects.create(whs_id=whs_id).first.extra`,
the result is list, match my expectations
but onece i use
`result= model_to_dict[item].`
`result['extra']=[\n {\n.....` 
this will make error for business code
i wish you can add a optional param like dump=True

**Comment by rpkilby** [comment]
Hi @clevertang. `dumps_for_display` has been removed in v3.
