### ISSUE TITLE
version 3.0.0 + Django 2 breaks the field deserialization from db

### ISSUE THREAD

**Issue by tramora** [rpkilby/jsonfield#242]
Hi,
In my environment (Django 2.2.1), it seems that the last version 3.0.0 of jsonfield (2020/02/15) breaks the field deserialization from db.

The automated tests against a sqlitedb raised the errors
- 2.1.1 : GOOD, returns dict as expected
- 3.0.0 : KO, returns Jsonfieldstring

I freezed the version to 2.1.1

**Comment by rpkilby** [comment]
Hi @tramora. Could you provide more information or an example test case? I tried the following, and had no issues.

```python
instance = JSONNotRequiredModel.objects.create(json={'data': 'data'})
instance = JSONNotRequiredModel.objects.get()
self.assertEqual(instance.json, {'data': 'data'})
```

**Comment by tramora** [comment]
you are right @rpkilby my initial issue was not precise enough to work with. Sorry for that.

In my case, a developer trusted too much the jsonfield 2.x and passed sometimes strings instead of a dict.

The following code works with the permissive 2.1.1 version but breaks in 3.0.0

```python
class JsonFieldTestCase(TestCase):

    tenantid = '00dc43d92ce34dba85a45401033590b1'

    def setUp(self):
        tenant = Tenant(tenantid=self.tenantid)
        # offending instruction : we should save directly a dict not a str
        tenant.json_path = json.dumps({'id': 'domain_id', 'name': 'domain_name', 'description': '', 'children': [{'id': '1', 'name': 'region1', 'description': '', 'children': [{}]}]})
        tenant.save()

    def test_get_jsonfield(self):
        tenant = Tenant.objects.get(tenantid=self.tenantid)
        assert tenant.json_path.__class__.__name__ == 'dict'

```
I'll have a look to the whole codebase but you confirm that the old behaviour was not desired ?

**Comment by rpkilby** [comment]
I'm not entirely sure, but my guess is that they might have been working around an old bug. 

That said, it's unnecessary to dump the data before saving. Just pass the dict directly. Also, you should probably type check the value with `assert isinstance(tenant.json_path, dict)`
