### ISSUE TITLE
Clean method fails on arbitrary string as a valid JSON

### ISSUE THREAD

**Issue by devbis** [rpkilby/jsonfield#243]
It is a duplicate of https://github.com/rpkilby/jsonfield2/issues/11 and possibly #202 and unfortunately, it is not fixed. 
I checked jsonfield2==4.0.0 and jsonfield==3.0.0 with Django==2.2.10

I want to save in JSONField either complex structures such as objects and lists or basic types like str. It should be fully JSON compliant. But I cannot run validation on the model with such JSONField attribute.

```
class Demo(models.Model):
    data = JSONField(blank=True)

demo = Demo.objects.create(data='some test string')
```

we can create a model without validation without any problems.
but when I run validation of the model
```
demo.full_clean()
```
it raises `ValidationError: {'data': ['Enter valid JSON.']}`
though 'some test string' is a valid JSON

**Comment by rpkilby** [comment]
Hi @devbis. I should have documented this, but I wanted to get 3.0 out the door. The short version is that this is a known bug, and decoded string values need to be wrapped in `JSONString`. Normally, `jsonfield` will handle this for you (specifically, form saving and loading from the db), but in your case, you've directly created an instance in Python with a decoded string value.

If you were to do

```python
demo = Demo.objects.create(data='some test string')
demo.refresh_from_db()
demo.full_clean()

# or
from jsonfield.json import JSONString
demo = Demo.objects.create(data=JSONString('some test string'))
demo.full_clean()
```

Then this would work.
