### ISSUE TITLE
Clarify relationship with jsonfield2 and django-jsonfield

### ISSUE THREAD

**Issue by Flimm** [rpkilby/jsonfield#244]
This project is published on Pypi as [`jsonfield`](https://pypi.org/project/jsonfield/). There are other packages with similar names, all for Django, which is confusing:

- [`jsonfield2` on Pypi](https://pypi.org/project/jsonfield2/)
- [`django-jsonfield` on Pypi](https://pypi.org/project/django-jsonfield/)

The similar names are causing confusion. For example, have a look at this comment https://github.com/django-notifications/django-notifications/issues/269#issuecomment-585088457 in the project `django-notifications`.

Please add to README.rst a warning pointing out the naming confusion. It also looks like Pypi packages `jsonfield` and `jsonfield2` are supposed to be merged now?

**Comment by rpkilby** [comment]
Hi @Flimm. Here are the details:

- This package has always been `jsonfield` on PyPI, but previously, the GH repository was `django-jsonfield`.
- This caused confusion, as there is also the `django-jsonfield` project on PyPI. 
- `jsonfield` wasn't actively maintained, so I created a fork called `jsonfield2`.
- However, I was recently granted ownership of `jsonfield`, merged my fork in, and then archived my fork as it was no longer necessary.
- Lastly, I changed the repo name from `django-jsonfield` to `jsonfield` to be consistent with the project name.

**Comment by rpkilby** [comment]
Also, I removed the paragraph about the `jsonfield`/`django-jsonfield` confusion, because the naming conflict is no longer there.

**Comment by Flimm** [comment]
Thank you for renaming the Github repo to `jsonfield` to match the Pypi name, that does help remove opportunities for confusion.

Since you're the maintainer of Pypi package `jsonfield2`, could you release an update on Pypi, updating the README of `jsonfield2`, to make it clear that it is deprecated in favour of `jsonfield`? Right now, if you visit https://pypi.org/project/jsonfield2/ , that isn't clear at all. It says it is a fork of `django-jsonfield`,  meaning the Pypi package `jsonfield`, and there is no mention that  `jsonfield2` is no longer needed since it has been merged back into `jsonfield`.

That would really help.

**Comment by rpkilby** [comment]
Good point. I updated the README on GitHub, but hadn't push that to PyPI. That should be fixed now. Thanks!

**Comment by Flimm** [comment]
Thank you!
