### ISSUE TITLE
JSONField fails in MySQL

### ISSUE THREAD

**Issue by appel268576** [rpkilby/jsonfield#25]
I recently added the JSONField to one of my Models and worked fine since both my local machine runs on Postgres and my Heroku instance too, since moving it over to production I have found that everytime I try and bring up an item containg a default value for MySQL it raises a validationerror.

class Item(models.Model):
    ...
    ...
    json = JSONField(default='{}')

raise ValidationError(msg)
ValidationError: [u"'' is not a valid JSON string."]

**Comment by adeelyounas** [comment]
:+1:

**Comment by nhammond** [comment]
Perhaps there was a regression? I just ran into this using django-jsonfield 2.0.1 with MySQL.

Added a new field to an existing model:

```
model Run(models.Model):
    ...
    notification_context = jsonfield.JSONField(blank=True)
    ...
```

Then applied the migration. Now when loading old models I see this ValidationError, while newer models load without a problem.

```
Run.objects.all()[36]
ValidationError: [u'Enter valid JSON'] 
```

The error was resolved by adding "null=True, default=None" to the field and setting all of the old values from "" to NULL.

```
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171003_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='notification_context',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True, validators=[api.models.validators.validate_notification_context]),
        ),
        migrations.RunSQL("UPDATE api_run SET notification_context = NULL WHERE notification_context = ''"),
    ]
```

**Comment by dmkoch** [comment]
A regression is very likely. Is there anyone on this thread who would be interested in adding both MySQL and Postgres-specific support to the test suite?
