### ISSUE TITLE
Issues between versions

### ISSUE THREAD

**Issue by senadibraimoski** [rpkilby/jsonfield#251]
Hi,

We have recently updated from jsonfield2 to jsonfield and we are experiencing issues when we have a dict data being passed in get_or_create().

The idea is we were using jsonfield2, jsonfield2==3.0.2 and when we update to latest jsonfield==3.1.0 the issue appears. In order to reproduce it you need to have a model lets say:

```
class MyModel:
    field_1 = models.CharField
    field_2 = JsonField()

   Meta:
      unique(field_1)

MyModel.objects.create(field_1='test', field_2={'foo':'bar'})
```

And while still on jsonfiield2==3.0.2 version create an entry in the database ( we use postgres ).

Now uninstall jsonfield2 and install latest jsonfield and try to do 

`MyModel.objects.get_or_create(field_1='test', field_2={'foo':'bar'})` - It will fail with `IntegrityError` and you will get "duplicate key value violates unique constraint" message. This is because if you just call `MyModel.objects.get(field_1='test', field_2={'foo':'bar'})` - it raises `ObjectDoesNotExist`, and then the above tries to call create but there is already a entry in the database with those params and there is a unique constraint in our case.

The most important thing is that this
`MyModel.objects.get(field_1='test', field_2={'foo':'bar'})` raises `ObjectDoesNotExist` when the entry clearly exists in the table

**Comment by rpkilby** [comment]
Hi @senadibraimoski. I added a test case in #252 but was unable to reproduce the issue. Could you provide feedback or open a separate PR that demonstrates the failure?

**Comment by senadibraimoski** [comment]
I can not - it's between versions - there is no way to create a PR to demonstrate this:

Create this with jsonfield2
```
MyModel.objects.create(field_1='test', field_2={'foo':'bar'})
```
uninstall jsonfiled2
install jsonfield

The just do this 
```
MyModel.objects.get(field_1='test', field_2={'foo':'bar'})
```

**Comment by rpkilby** [comment]
> it's between versions

Oh, right 🤦‍♂ 

Alright, I tried recreating this locally, but wasn't able to generate the error. Here's the model I used:

```python
class Test(models.Model):
    text = models.CharField(max_length=32, unique=True)
    data = JSONField()
```

Using `jsonfield2==3.0.2` and `Django==2.2`, I generated and ran the migration.

In the Django shell:
```python
In [1]: from app.models import Test                                                                                                  

In [2]: Test.objects.get_or_create(text='abc', data={'a': 'b'})                                                                      
Out[2]: (<Test: Test object (1)>, True)
```
Uninstalled jsonfield2, then ran `pip install jsonfield`. Again, in the Django shell:
```python
In [1]: from app.models import Test                                                                                                  

In [2]: Test.objects.get_or_create(text='abc', data={'a': 'b'})                                                                      
Out[2]: (<Test: Test object (1)>, False)
```

Is there anything I missed? Also, could you dump the contents of the row using the dbshell? I'm wondering if there was a serialization bug that's causing the value to appear different.

**Comment by senadibraimoski** [comment]
Hey @rpkilby I did also update from Django 2 to Django 3.0.4. Sure will provide more info over the weekend as well - your example is on the point our DB backend is Postgres as well I failed to mention that


So wee used Django Django==2.2.7, jsonfield2==3.0.2 - and we had those model present in the DB already. Now we switched to Django==3.0.4 and jsonfield==3.1.0 - and we got the error. When we use Django==3.0.4 and jsonfield==3.0.2 works fine.

I will provide more info during the weekend its 1:30am where I am (London) so I have to go to bed.

**Comment by rpkilby** [comment]
> Postgres as well I failed to mention that

You did mention it in your OP. 

> When we use Django==3.0.4 and jsonfield==3.0.2 works fine.

My assumption here is that the Django version isn't going to affect the outcome, although it wouldn't hurt to test.

**Comment by rpkilby** [comment]
Hi @senadibraimoski. Any update or were you able to resolve this?

**Comment by senadibraimoski** [comment]
Yes @rpkilby it was an error on my part. The migrations were not being executed due to some backwards incompatible structure between me moving from Django 2 to 3.05, sorry for the false alarm - it was a proper heisenbug

**Comment by rpkilby** [comment]
No worries - glad you were able to figure it out!
