### ISSUE TITLE
Can't save {} into JSONField in Django admin

### ISSUE THREAD

**Issue by teolisitza** [rpkilby/jsonfield#50]
I get a message that the field cannot be empty. In my models.py:

`json_extras = JSONField(max_length=5000, load_kwargs={'object_pairs_hook': collections.OrderedDict})`

When I attempt to save an empty JSON document ( {} ) at the admin I get the error message:

**This field is required.**

I'm on Python 2.7.3 + django 1.4.5 on debian wheezy.

Thank you for any time spent on this issue.

**Comment by wizravi** [comment]
JSONField(null=True, blank=True) is this construct valid?
