### ISSUE TITLE
Problems withs PostGres 9.3, JSON Field and Query Distinct

### ISSUE THREAD

**Issue by ewjoachim** [rpkilby/jsonfield#57]
As mentionned in #47, using ".distinct()", which is used by the admin panel creating users but also in several other cases in django processes, triggers the same bug as #47 describes.

A workaround has been found by @mkhattab : 
The work around for this in the Django admin is to subclass `QuerySet` and `Manager` and override the `distinct` method [to remove the JSON fields from it].

What would be the definite fix ?

**Comment by Xowap** [comment]
If I might, the `jsonb` type appeared in PostgreSQL 9.4, and won't be causing any issue with `DISTINCT` anymore. Having an actual JSON support from the DB is *useful* in my application, not using the native PostgreSQL type is not an option, so I'd suggest to get native PostgreSQL type support merged back :)

**Comment by bradjasper** [comment]
@Xowap I'd be open to taking another look at this now that it looks like some of the support in django has been improved. Plan is to schedule some work on this in the next couple of weeks and this is something I can look at.

**Comment by cancan101** [comment]
Any updates on getting support for using the native `jsonb`?

**Comment by jeverling** [comment]
Hi @bradjasper any news on jsonb support?

**Comment by AGASS007** [comment]
It might be a problem if you cannot easily upgrade Django, but jsonb is natively supported by 1.9

https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/#jsonfield
