### ISSUE TITLE
Default values seem to be python serialized (instead of json) in adminUI

### ISSUE THREAD

**Issue by gilpinheiro** [rpkilby/jsonfield#69]
Initializing a JSONField with a given default value:
properties = JSONField(default = {"welcome":1})

Results in the admin ui having:
{'welcome':1} 
pre-populated in the form field box, which is not json serialized (will throw an error when you attempt to save since the json parser only accepts double quoted strings (i.e. {"welcome":1}

It seemed like the right behaviour according to (https://github.com/bradjasper/django-jsonfield/issues/20 ) would either to deal appropriately with the dict, or perhaps raise an error (expecting the default parameter to be a pre-serialized string).

**Comment by ellulpatrick** [comment]
The problem with "using a json string as default string" is that if you save a new instance of the model *without* going through a form, like directly from a django script, that default is taken as a json string and saved as an escaped string in the database. hence why it works when it is simply "{}", but not quite when there are actual attributes in the json object. This problem still needs addressing somehow.
