### ISSUE TITLE
JSONField not deserialized in certain cases when a non-Autofield primary key is used

### ISSUE THREAD

**Issue by brki** [rpkilby/jsonfield#92]
If a non-Autofield primary key is defined for a model with a JSONField, in some cases the JSONField will not be deserialized when accessed.

Failing tests added here:
https://github.com/brki/django-jsonfield/compare/failing-tests-with-non-autofield-pk

For these test cases, it seems that django has not specified the primary key yet when this code gets executed: https://github.com/bradjasper/django-jsonfield/blob/b0b1ae4b3aaa22883582d3896fc17d38248768db/jsonfield/fields.py#L75

As a result, the json field is not deserialized. Instead, it is returned as a string containing json.

**Comment by rpkilby** [comment]
Hi all. Closing this, as it is related to South. Note that I did run the tests from brki's fork just in case, and no failures occurred.
