### ISSUE TITLE
JSONField doesn't call functions specified in the validators keyword argument when used in a mixin

### ISSUE THREAD

**Issue by robdennis** [rpkilby/jsonfield#94]
consider this made up class (a sanitized version of what I'm dealing with in my code)

``` python
from django.db import models
from django.core.exceptions import ValidationError
from jsonfield import JSONField

def test_validator(value):
    raise ValidationError("I'm failing on purpose")

class MyMixin(models.Model):
    class Meta:
        abstract = True
    test = JSONField(default={}, blank=True, validators=[test_validator])

class MyModel(models.Model, MyMixin):
    pass
```

full_clean does not appear to raise the expected validation error:

``` python
>>> test = MyModel(test=None)
>>> test.full_clean()
>>>
```

there don't appear to be any unit tests asserting that validators are being called, and a quick view of the source doesn't show any obvious thing where you're throwing the validators away or where it's intentional that they won't be called.

Some testing points out that if my field was on the class, instead of the mixin, the validator would be called. But I haven't gone deep into figuring out the difference

Is this expected behavior?

**Comment by rpkilby** [comment]
Hi all. I realize this is a long-dormant issue, but wanted to followup. Anyway, I think the issue was related to the test itself. Looking at [`run_validators`](https://github.com/django/django/blob/1.7/django/db/models/fields/__init__.py#L457-L459), they aren't ran when given an "empty" value.
